### INGRESS ###

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
    {{- with .Values.ingress.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: cake.oebinu.com
    http:
      paths:
        - path: /{{ .Values.banana.image.tag }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.banana.image.tag }}-svc
              port:
                number: {{ .Values.tomato.service.port }}
        - path: /{{ .Values.tomato.image.tag }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.tomato.image.tag }}-svc
              port:
                number: {{ .Values.tomato.service.port }}
